#!/bin/sh
# Evolution API entrypoint with optional proxy support
# If PROXY_HOST + PROXY_PORT are set, all network traffic
# (including WebSocket to WhatsApp) goes through the proxy.

if [ -n "$PC_PROXY_HOST" ] && [ -n "$PC_PROXY_PORT" ]; then
    echo "[Evolution API] 🌐 Proxychains enabled: $PC_PROXY_HOST:$PC_PROXY_PORT (type: ${PC_PROXY_TYPE:-socks5})"

    # Build proxy line (with or without auth)
    PTYPE="${PC_PROXY_TYPE:-socks5}"
    if [ -n "$PC_PROXY_USER" ] && [ -n "$PC_PROXY_PASS" ]; then
        PROXY_LINE="$PTYPE $PC_PROXY_HOST $PC_PROXY_PORT $PC_PROXY_USER $PC_PROXY_PASS"
    else
        PROXY_LINE="$PTYPE $PC_PROXY_HOST $PC_PROXY_PORT"
    fi

    # Generate proxychains config at runtime
    cat > /tmp/proxychains.conf << EOF
# Auto-generated by entrypoint.sh
strict_chain
# NO proxy_dns — let Docker internal DNS resolve postgres/redis
# WhatsApp DNS resolves locally, only TCP goes through proxy
tcp_read_time_out 15000
tcp_connect_time_out 8000

# Exclude Docker internal networks from proxy
localnet 127.0.0.0/255.0.0.0
localnet 10.0.0.0/255.0.0.0
localnet 172.0.0.0/255.0.0.0
localnet 192.168.0.0/255.255.0.0

[ProxyList]
$PROXY_LINE
EOF

    echo "[Evolution API] Proxychains ready (no proxy_dns, localnet active)"
    exec proxychains4 -q -f /tmp/proxychains.conf node dist/main
else
    echo "[Evolution API] 🔗 Direct connection (no proxy)"
    exec node dist/main
fi
